Encoder.Encoder Class Reference
A quadrature encoder class for position and velocity measurement.
Public Member Functions
__init__ (self, motor, Timer tim, chA_pin, int chA_num, chB_pin, int chB_num)
Initialize an encoder.
float position (self)
Get the current wheel position.
None position (self, float value)
Set the current wheel position.
float velocity (self)
Get the current wheel velocity.
None update (self)
Update encoder position and velocity.
float get_data (self)
Return the most recent velocity measurement.
None zero (self)
Reset encoder displacement and timing.
Public Member Functions inherited from Sensor.Sensor
set_attr (cls, K="Kp", value=0.0)
None __init__ (self)
None update_dt (self)
None reset_timing (self)
Public Attributes
motor = motor
int prev_count = 0
int delta = 0
ar = tim.period()
tim = tim
chA_pin = Pin(chA_pin, mode=Pin.IN)
chB_pin = Pin(chB_pin, mode=Pin.IN)
chA = tim.channel(chA_num, pin=self.chA_pin, mode=Timer.ENC_AB)
chB = tim.channel(chB_num, pin=self.chB_pin, mode=Timer.ENC_AB)
Public Attributes inherited from Sensor.Sensor
int dt = 0
Static Public Attributes
float Kp = 0.05
float Ki = 0.05
int Kd = 0
float Kw = 0.10
float Kff = 0.075
float PWM_startl = 5.5
float PWM_startr = 5.5
Protected Attributes
int _position = 0
Protected Attributes inherited from Sensor.Sensor
_prev_t = ticks_us()
Detailed Description
A quadrature encoder class for position and velocity measurement.
This class configures a timer in encoder mode and provides wheel position (radians) and velocity (mm/s). It is compatible with the closed-loop control system through the get_data() interface.
Definition at line 29 of file Encoder.py.
Constructor & Destructor Documentation
__init__()
Encoder.Encoder.__init__ (self, motor, Timer tim, chA_pin, int chA_num, chB_pin, int chB_num)
Initialize an encoder.
Parameters
motor The motor this encoder belongs to
tim pyb.Timer configured for encoder mode
chA_pin Pin for channel A input
chA_num Timer channel number for channel A
chB_pin Pin for channel B input
chB_num Timer channel number for channel B
Definition at line 49 of file Encoder.py.
    def __init__(self, motor, tim: Timer, chA_pin, chA_num: int, chB_pin, chB_num: int):
        super().__init__()
 
        self.motor = motor
        self._position = 0 # Accumulated wheel position (rad)
        self.prev_count = 0 # Last timer count
        self.delta = 0 # Tick difference between updates
 
        self.ar = tim.period() # Auto-reload value
        self.tim = tim
 
        # Configure pins and timer channels
        self.chA_pin = Pin(chA_pin, mode=Pin.IN)
        self.chB_pin = Pin(chB_pin, mode=Pin.IN)
        self.chA = tim.channel(chA_num, pin=self.chA_pin, mode=Timer.ENC_AB)
        self.chB = tim.channel(chB_num, pin=self.chB_pin, mode=Timer.ENC_AB)
 
References __init__().
Member Function Documentation
get_data()
 float Encoder.Encoder.get_data (self)
Return the most recent velocity measurement.
Allows this object to be used as a generic sensor in controllers.
Returns
Velocity in mm/s.
Reimplemented from Sensor.Sensor.
Definition at line 122 of file Encoder.py.
    def get_data(self) -> float:
        return self.velocity
 
References velocity().
position() [1/2]
 float Encoder.Encoder.position (self)
Get the current wheel position.
Returns
Wheel angle in radians (signed).
Definition at line 70 of file Encoder.py.
    def position(self) -> float:
        return -self._position
 
References _position.
position() [2/2]
 None Encoder.Encoder.position (self, float value)
Set the current wheel position.
Parameters
value New wheel position in radians.
Definition at line 77 of file Encoder.py.
    def position(self, value: float) -> None:
        self._position = -value
 
References _position.
update()
 None Encoder.Encoder.update (self)
Update encoder position and velocity.
Reads timer counter
Computes tick difference with wrap-around handling
Converts ticks to radians
Updates total position
Updates dt for timing
Definition at line 98 of file Encoder.py.
    def update(self) -> None:
        count = self.tim.counter()
        self.delta = count - self.prev_count
        self.prev_count = count
 
        # Wrap-around correction
        half_range = (self.ar + 1) / 2
        if self.delta < -half_range:
            self.delta += self.ar + 1
        if self.delta > half_range:
            self.delta -= self.ar + 1
 
        # Convert to radians and accumulate
        self.delta *= RomiProps.ticks_to_rads
        self._position += self.delta
 
        # Update timing from Sensor base class
        self.update_dt()
 
References _position, ar, delta, prev_count, tim, and Sensor.Sensor.update_dt().
velocity()
 float Encoder.Encoder.velocity (self)
Get the current wheel velocity.
Returns velocity computed using most recent tick delta and dt.
Returns
Wheel velocity in mm/s.
Definition at line 86 of file Encoder.py.
    def velocity(self) -> float:
        if self.delta == 0 or self.dt == 0:
            return 0
        return -(self.delta * RomiProps.wheel_radius * 1e6) / self.dt
 
References delta, and Sensor.Sensor.dt.
zero()
 None Encoder.Encoder.zero (self)
Reset encoder displacement and timing.
Useful when synchronizing encoder readings with heading or odometry.
Definition at line 128 of file Encoder.py.
    def zero(self) -> None:
        self._position = 0
        self.prev_count = self.tim.counter()
        self.delta = 0
        self.reset_timing()
References _position, delta, prev_count, Sensor.Sensor.reset_timing(), and tim.
Member Data Documentation
_position
int Encoder.Encoder._position = 0 [protected]
Definition at line 53 of file Encoder.py.
ar
Encoder.Encoder.ar = tim.period()
Definition at line 57 of file Encoder.py.
chA
Encoder.Encoder.chA = tim.channel(chA_num, pin=self.chA_pin, mode=Timer.ENC_AB)
Definition at line 63 of file Encoder.py.
chA_pin
Encoder.Encoder.chA_pin = Pin(chA_pin, mode=Pin.IN)
Definition at line 61 of file Encoder.py.
chB
Encoder.Encoder.chB = tim.channel(chB_num, pin=self.chB_pin, mode=Timer.ENC_AB)
Definition at line 64 of file Encoder.py.
chB_pin
Encoder.Encoder.chB_pin = Pin(chB_pin, mode=Pin.IN)
Definition at line 62 of file Encoder.py.
delta
int Encoder.Encoder.delta = 0
Definition at line 55 of file Encoder.py.
Kd
int Encoder.Encoder.Kd = 0 [static]
Definition at line 34 of file Encoder.py.
Kff
float Encoder.Encoder.Kff = 0.075 [static]
Definition at line 36 of file Encoder.py.
Ki
float Encoder.Encoder.Ki = 0.05 [static]
Definition at line 33 of file Encoder.py.
Kp
float Encoder.Encoder.Kp = 0.05 [static]
Definition at line 32 of file Encoder.py.
Kw
float Encoder.Encoder.Kw = 0.10 [static]
Definition at line 35 of file Encoder.py.
motor
Encoder.Encoder.motor = motor
Definition at line 52 of file Encoder.py.
prev_count
int Encoder.Encoder.prev_count = 0
Definition at line 54 of file Encoder.py.
PWM_startl
float Encoder.Encoder.PWM_startl = 5.5 [static]
Definition at line 38 of file Encoder.py.
PWM_startr
float Encoder.Encoder.PWM_startr = 5.5 [static]
Definition at line 39 of file Encoder.py.
tim
Encoder.Encoder.tim = tim
Definition at line 58 of file Encoder.py.
The documentation for this class was generated from the following file:
Lab Final/Files On Romi/Encoder.py