IMU.IMU Class Reference
Classes
class reg
Public Member Functions
__init__ (self, I2C i2c_object, Pin reset_pin)
reset (self)
float get_data (self)
set_mode (self, int mode)
tuple get_calibration_status (self)
tuple get_calibration_coefficients (self)
bool calibrate (self)
tuple[float, float, float] get_euler_angles (self)
float get_imu_heading (self)
float get_heading (self)
zero_heading (self)
float get_yaw_rate (self)
Public Member Functions inherited from Sensor.Sensor
set_attr (cls, K="Kp", value=0.0)
None __init__ (self)
None update_dt (self)
None reset_timing (self)
Public Attributes
i2c = i2c_object
reset_pin = reset_pin
bool calibrated = False
int convert_reg_to_rad = 900
int prev_imu_heading = 0
int heading = 0
int ar = 2 * pi
float delta = self.get_imu_heading() - self.prev_imu_heading
Public Attributes inherited from Sensor.Sensor
int dt = 0
Static Public Attributes
int DEV_ADDR = 0x28
int default_mode_set = 5
float Kp = 0.15
float Ki = 0.20
float Kd = 0.00
Protected Member Functions
_read_reg (self, tuple reg)
_write_reg (self, tuple reg, str input)
Protected Attributes
_buf = bytearray((0 for _ in range(22)))
Protected Attributes inherited from Sensor.Sensor
_prev_t = ticks_us()
Detailed Description
Definition at line 9 of file IMU.py.
Constructor & Destructor Documentation
__init__()
IMU.IMU.__init__ (self, I2C i2c_object, Pin reset_pin)
Definition at line 56 of file IMU.py.
    def __init__(self, i2c_object: I2C, reset_pin: Pin):
        super().__init__()
        self.i2c = i2c_object # the pyb board is the controller, meaning the IMU is the peripheral
        self.reset_pin = reset_pin
        self._buf = bytearray((0 for _ in range(22))) # buffer for unpacking. Each element is a byte
        self.calibrated = False
        self.convert_reg_to_rad = 900
        self.prev_imu_heading = 0
        self.heading = 0
        self.ar = 2 * pi
        self.reset()
 
References __init__().
Member Function Documentation
_read_reg()
IMU.IMU._read_reg (self, tuple reg) [protected]
Definition at line 81 of file IMU.py.
    def _read_reg(self, reg: tuple):
        # determine number of bytes from reg read code
        length = calcsize(reg[1])
 
        # Create a memoryview object of the right size
        buf = memoryview(self._buf)[:length]
 
        # Read the the I2C bytes into memoryview
        self.i2c.mem_read(buf, self.DEV_ADDR, reg[0])
 
        return unpack_from(reg[1], buf)
 
References _buf, DEV_ADDR, and i2c.
_write_reg()
IMU.IMU._write_reg (self, tuple reg, str input) [protected]
Definition at line 93 of file IMU.py.
    def _write_reg(self, reg: tuple, input: str):
        # Writes a string input to the IMU: ie input = '01110xxx'
        # This write functionality can work on 8 or 16 bits
        # ASSUMED THAT CONFIGMODE IS SET APPROPRIATELY BEFORE CALLING THIS FUNCTION
 
        # determine number of bytes in register location
        length = calcsize(reg[1])
        if length > 2 or len(input) // 8 != length:
            raise ValueError("Write to register is not the correct length")
 
        # Create and mask and or mask
        and_mask = 0b1111_1111 if length == 1 else 0b1111_1111_1111_1111
        or_mask = 0b0000_0000 if length == 1 else 0b0000_0000_0000_0000
        for char_index in range(len(input)):
            char = input[-char_index - 1]
            if char == "x" or char == "X":
                continue # and mask is already set, or mask is already cleared
            elif char == "0":
                and_mask &= ~(1 << (char_index)) # clear the and bit
            elif char == "1":
                and_mask &= ~(1 << (char_index)) # clear the and bit
                or_mask |= 1 << (char_index) # set the or bit
            else:
                raise ValueError("mask chars must be '0','1','x', or 'X'")
 
        self.i2c.mem_write(
            ((self._read_reg(reg)[0] & and_mask) | or_mask),
            self.DEV_ADDR,
            reg[0],
            addr_size=(8 if length == 1 else 16),
        )
 
References _read_reg(), DEV_ADDR, and i2c.
calibrate()
 bool IMU.IMU.calibrate (self)
Definition at line 151 of file IMU.py.
    def calibrate(self) -> bool:
        if "IMU_cal.txt" in listdir():
            # Calibration data is present
            self.set_mode(0)
            print("Found IMU calibration data, skipping calibration")
            with open("IMU_cal.txt", "r") as file:
                entries = file.readline().strip().split(",")
                if len(entries) != 11:
                    raise ValueError("Calibration data length != expected length")
 
                for idx, coeff_reg in enumerate(IMU.reg.calibration_coefficients):
                    self._write_reg(coeff_reg, entries[idx])
 
                self.calibrated = True
                self.set_mode(IMU.default_mode_set)
                return True
        else:
            print("No IMU calibration data found")
            self.set_mode(5) # set to NDOF mode for calibration
 
            prev_cal = cur_cal = 0
            while not (cur_cal & 0b0011_0011 == 0b0011_0011): # only check GYR and MAG calibration
                if prev_cal != cur_cal:
                    print(f"{cur_cal:08b}")
                    prev_cal = cur_cal
 
                cur_cal = self.get_calibration_status()[0] # Update cur_cal before checking
                if cur_cal & 0b0011_0011 == 0b0011_0011:
                    self.set_mode(0)
                    with open("IMU_cal.txt", "w") as f:
                        coefs = ",".join(f"{s & 0xFFFF:016b}" for s in self.get_calibration_coefficients())
                        f.write(f"{coefs}\n")
                        print(f"{coefs}")
                    print("IMU Calibration Coefficients Saved")
                    self.calibrated = True
                    self.set_mode(IMU.default_mode_set)
                    return True
                delay(100) # delay(ms) to allow IMU to settle
        return False
 
References _write_reg(), calibrated, get_calibration_coefficients(), get_calibration_status(), and set_mode().
get_calibration_coefficients()
 tuple IMU.IMU.get_calibration_coefficients (self)
Definition at line 148 of file IMU.py.
    def get_calibration_coefficients(self) -> tuple:
        return tuple(self._read_reg(coeff_reg)[0] for coeff_reg in IMU.reg.calibration_coefficients)
 
References _read_reg().
get_calibration_status()
 tuple IMU.IMU.get_calibration_status (self)
Definition at line 145 of file IMU.py.
    def get_calibration_status(self) -> tuple:
        return self._read_reg(IMU.reg.CALIB_STAT)
 
References _read_reg().
get_data()
 float IMU.IMU.get_data (self)
Reimplemented from Sensor.Sensor.
Definition at line 78 of file IMU.py.
    def get_data(self) -> float:
        return self.get_heading()
 
References get_heading().
get_euler_angles()
 tuple[float, float, float] IMU.IMU.get_euler_angles (self)
Definition at line 191 of file IMU.py.
    def get_euler_angles(self) -> tuple[float, float, float]:
        # order: head, rolled, pitched
        return tuple(x / -self.convert_reg_to_rad for x in self._read_reg(IMU.reg.EUL_DATA_ALL))
 
References _read_reg(), and convert_reg_to_rad.
get_heading()
 float IMU.IMU.get_heading (self)
Definition at line 198 of file IMU.py.
    def get_heading(self) -> float:
        self.delta = self.get_imu_heading() - self.prev_imu_heading
        self.prev_imu_heading = self.get_imu_heading()
 
        # Overflow
        if self.delta < -self.ar / 2:
            self.delta += self.ar
        # Underflow
        if self.delta > self.ar / 2:
            self.delta -= self.ar
 
        self.heading += self.delta
 
        return self.heading
 
get_imu_heading()
 float IMU.IMU.get_imu_heading (self)
Definition at line 195 of file IMU.py.
    def get_imu_heading(self) -> float:
        return -self._read_reg(IMU.reg.EUL_HEADING)[0] / self.convert_reg_to_rad
 
References _read_reg(), and convert_reg_to_rad.
get_yaw_rate()
 float IMU.IMU.get_yaw_rate (self)
Definition at line 218 of file IMU.py.
    def get_yaw_rate(self) -> float:
        return self._read_reg(IMU.reg.GYRO_DATA_Z)[0] / self.convert_reg_to_rad
References _read_reg(), and convert_reg_to_rad.
reset()
IMU.IMU.reset (self)
Definition at line 68 of file IMU.py.
    def reset(self):
        self.reset_pin.value(0)
        self.reset_pin.value(1)
        delay(700) # delay(ms) to allow IMU to reset
 
        self._write_reg(IMU.reg.AXIS_REMAP_CONFIG, "00100001") # P3
        self._write_reg(IMU.reg.AXIS_REMAP_SIGN, "xxxxxx10")
        self._write_reg(IMU.reg.UNIT_SEL, "xxx1x110") # degF, rads, rad/s, m/s^2
 
References _write_reg(), and reset_pin.
set_mode()
IMU.IMU.set_mode (self, int mode)
Definition at line 129 of file IMU.py.
    def set_mode(self, mode: int):
        if mode == 0:
            self._write_reg(IMU.reg.OPR_MODE, "xxxx0000") # 0: CONFIGMODE
        elif mode == 1:
            self._write_reg(IMU.reg.OPR_MODE, "xxxx1000") # 1: IMU
        elif mode == 2:
            self._write_reg(IMU.reg.OPR_MODE, "xxxx1001") # 2: COMPASS
        elif mode == 3:
            self._write_reg(IMU.reg.OPR_MODE, "xxxx1010") # 3: M4G
        elif mode == 4:
            self._write_reg(IMU.reg.OPR_MODE, "xxxx1011") # 4: NDOF_FMC_OFF
        elif mode == 5:
            self._write_reg(IMU.reg.OPR_MODE, "xxxx1100") # 5: NDOF
        else:
            raise ValueError("Invalid mode")
 
References _write_reg().
zero_heading()
IMU.IMU.zero_heading (self)
Definition at line 213 of file IMU.py.
    def zero_heading(self):
        self.heading = 0
        self.prev_imu_heading = self.get_imu_heading()
        self.delta = 0
 
References Encoder.Encoder.delta, delta, get_imu_heading(), heading, and prev_imu_heading.
Member Data Documentation
_buf
IMU.IMU._buf = bytearray((0 for _ in range(22))) [protected]
Definition at line 60 of file IMU.py.
ar
int IMU.IMU.ar = 2 * pi
Definition at line 65 of file IMU.py.
calibrated
bool IMU.IMU.calibrated = False
Definition at line 61 of file IMU.py.
convert_reg_to_rad
int IMU.IMU.convert_reg_to_rad = 900
Definition at line 62 of file IMU.py.
default_mode_set
int IMU.IMU.default_mode_set = 5 [static]
Definition at line 12 of file IMU.py.
delta
float IMU.IMU.delta = self.get_imu_heading() - self.prev_imu_heading
Definition at line 199 of file IMU.py.
DEV_ADDR
IMU.IMU.DEV_ADDR = 0x28 [static]
Definition at line 11 of file IMU.py.
heading
int IMU.IMU.heading = 0
Definition at line 64 of file IMU.py.
i2c
IMU.IMU.i2c = i2c_object
Definition at line 58 of file IMU.py.
Kd
float IMU.IMU.Kd = 0.00 [static]
Definition at line 17 of file IMU.py.
Ki
float IMU.IMU.Ki = 0.20 [static]
Definition at line 16 of file IMU.py.
Kp
float IMU.IMU.Kp = 0.15 [static]
Definition at line 15 of file IMU.py.
prev_imu_heading
int IMU.IMU.prev_imu_heading = 0
Definition at line 63 of file IMU.py.
reset_pin
IMU.IMU.reset_pin = reset_pin
Definition at line 59 of file IMU.py.
The documentation for this class was generated from the following file:
Lab Final/Files On Romi/IMU.py