IR_Sensor.IRSensor Class Reference
Public Member Functions
__init__ (self, int id, ADC_pin)
float get_data (self)
read (self)
Public Member Functions inherited from Sensor.Sensor
set_attr (cls, K="Kp", value=0.0)
None __init__ (self)
None update_dt (self)
None reset_timing (self)
Public Attributes
id = id
tuple location = (self.id - 7) * 8
ADC_pin = Pin(ADC_pin, mode=Pin.ANALOG)
ADC = ADC(self.ADC_pin)
int white = 0
int black = 1
Public Attributes inherited from Sensor.Sensor
int dt = 0
Additional Inherited Members
Protected Attributes inherited from Sensor.Sensor
_prev_t = ticks_us()
Detailed Description
Definition at line 5 of file IR_Sensor.py.
Constructor & Destructor Documentation
__init__()
IR_Sensor.IRSensor.__init__ (self, int id, ADC_pin)
Definition at line 6 of file IR_Sensor.py.
    def __init__(self, id: int, ADC_pin):
        super().__init__()
        # Sensor number from 1 to 13. ASSUMES 13 IS RIGHT MOST SENSOR
        self.id = id
        # location in mm from line sensor center. ASSUMES 13 IS RIGHT WHICH IS POSITIVE
        self.location = (self.id - 7) * 8
        self.ADC_pin = Pin(ADC_pin, mode=Pin.ANALOG)
        self.ADC = ADC(self.ADC_pin)
        self.white = 0
        self.black = 1
 
References __init__().
Member Function Documentation
get_data()
 float IR_Sensor.IRSensor.get_data (self)
Reimplemented from Sensor.Sensor.
Definition at line 18 of file IR_Sensor.py.
    def get_data(self) -> float:
        return (self.ADC.read() - self.white) / (self.black - self.white)
 
References ADC, black, read(), and white.
read()
IR_Sensor.IRSensor.read (self)
Definition at line 21 of file IR_Sensor.py.
    def read(self):
        return self.ADC.read()
References ADC, and read().
Member Data Documentation
ADC
IR_Sensor.IRSensor.ADC = ADC(self.ADC_pin)
Definition at line 13 of file IR_Sensor.py.
ADC_pin
IR_Sensor.IRSensor.ADC_pin = Pin(ADC_pin, mode=Pin.ANALOG)
Definition at line 12 of file IR_Sensor.py.
black
int IR_Sensor.IRSensor.black = 1
Definition at line 15 of file IR_Sensor.py.
id
IR_Sensor.IRSensor.id = id
Definition at line 9 of file IR_Sensor.py.
location
tuple IR_Sensor.IRSensor.location = (self.id - 7) * 8
Definition at line 11 of file IR_Sensor.py.
white
IR_Sensor.IRSensor.white = 0
Definition at line 14 of file IR_Sensor.py.
The documentation for this class was generated from the following file:
Lab Final/Files On Romi/IR_Sensor.py