task_share.Queue Class Reference
A queue which is used to transfer data from one task to another.
Public Member Functions
__init__ (self, type_code, size, thread_protect=False, overwrite=False, name=None)
Initialize a queue object to carry and buffer data between tasks.
put (self, item, in_ISR=False)
Put an item into the queue.
get (self, in_ISR=False)
Read an item from the queue.
any (self)
Check if there are any items in the queue.
empty (self)
Check if the queue is empty.
full (self)
Check if the queue is full.
num_in (self)
Check how many items are in the queue.
clear (self)
Remove all contents from the queue.
__repr__ (self)
This method puts diagnostic information about the queue into a string.
Public Member Functions inherited from task_share.BaseShare
__init__ (self, type_code, thread_protect=True, name=None)
Create a base queue object when called by a child class initializer.
Static Public Attributes
int ser_num = 0
A counter used to give serial numbers to queues for diagnostic use.
Protected Attributes
_size = size
_overwrite = overwrite
str _name = None else "Queue" + str(Queue.ser_num)
_buffer = array.array(type_code, range(size))
int _wr_idx = 0
int _num_items = self._size
# Record maximum fillage _max_full
int _rd_idx = 0
Protected Attributes inherited from task_share.BaseShare
_type_code = type_code
_thread_protect = thread_protect
Detailed Description
A queue which is used to transfer data from one task to another.
If parameter 'thread_protect' is True when a queue is created, transfers of data will be protected from corruption in the case that one task might interrupt another due to use in a pre-emptive multithreading environment or due to one task being run as an interrupt service routine.
An example of the creation and use of a queue is as follows:
import task_share
# This queue holds unsigned short (16-bit) integers
my_queue = task_share.Queue ('H', 100, name="My Queue")
# Somewhere in one task, put data into the queue
my_queue.put (some_data)
# In another task, read data from the queue
something = my_queue.get ()
Definition at line 98 of file task_share.py.
Constructor & Destructor Documentation
__init__()
task_share.Queue.__init__ (self, type_code, size, thread_protect = False, overwrite = False, name = None)
Initialize a queue object to carry and buffer data between tasks.
This method sets up a queue by allocating memory for the contents and setting up the components in an empty configuration.
Each queue can only carry data of one particular type which must be chosen from the following list. The data type is specified by a one-letter type code which is given as for the Python array.array type, which can be any of the following:
31
bg=,font= bg=,font= bg=,font=
b (signed char) B (unsigned char) 8 bit integers
h (signed short) H (unsigned short) 16 bit integers
i (signed int) I (unsigned int) 32 bit integers (probably)
l (signed long) L (unsigned long) 32 bit integers
q (signed long long) Q (unsigned long long) 64 bit integers
f (float) d (double-precision float)
Parameters
type_code The type of data items which the queue can hold
size The maximum number of items which the queue can hold
thread_protect True if mutual exclusion protection is used
overwrite If True, oldest data will be overwritten with new data if the queue becomes full
name A short name for the queue, default QueueN where N is a serial number for the queue
Definition at line 128 of file task_share.py.
    def __init__(self, type_code, size, thread_protect=False, overwrite=False, name=None):
        # First call the parent class initializer
        super().__init__(type_code, thread_protect, name)
 
        self._size = size
        self._overwrite = overwrite
        self._name = str(name) if name != None else "Queue" + str(Queue.ser_num)
        Queue.ser_num += 1
 
        # Allocate memory in which the queue's data will be stored
        try:
            self._buffer = array.array(type_code, range(size))
        except MemoryError:
            self._buffer = None
            raise
        except ValueError:
            self._buffer = None
            raise
 
        # Initialize pointers to be used for reading and writing data
        self.clear()
 
        # Since we may have allocated a bunch of memory, call the garbage
        # collector to neaten up what memory is left for future use
        gc.collect()
 
References __init__().
Member Function Documentation
__repr__()
task_share.Queue.__repr__ (self)
This method puts diagnostic information about the queue into a string.
It shows the queue's name and type as well as the maximum number of items and queue size.
Definition at line 295 of file task_share.py.
    def __repr__(self):
        return "{:<12s} Queue<{:s}> Max Full {:d}/{:d}".format(
            self._name, type_code_strings[self._type_code], self._max_full, self._size
        )
 
 
# ============================================================================
 
 
References _max_full, _name, _size, and task_share.BaseShare._type_code.
any()
task_share.Queue.any (self)
Check if there are any items in the queue.
Returns True if there are any items in the queue and False if the queue is empty.
Returns
True if items are in the queue, False if not
Definition at line 254 of file task_share.py.
    def any(self):
        return self._num_items > 0
 
References _num_items.
clear()
task_share.Queue.clear (self)
Remove all contents from the queue.
Definition at line 285 of file task_share.py.
    def clear(self):
        self._rd_idx = 0
        self._wr_idx = 0
        self._num_items = 0
        self._max_full = 0
 
References _max_full, _num_items, _rd_idx, and _wr_idx.
empty()
task_share.Queue.empty (self)
Check if the queue is empty.
Returns True if there are no items in the queue and False if there are any items therein.
Returns
True if queue is empty, False if it's not empty
Definition at line 263 of file task_share.py.
    def empty(self):
        return self._num_items <= 0
 
References _num_items.
full()
task_share.Queue.full (self)
Check if the queue is full.
This method returns True if the queue is already full and there is no room for more data without overwriting existing data.
Returns
True if the queue is full
Definition at line 272 of file task_share.py.
    def full(self):
        return self._num_items >= self._size
 
References _num_items, and _size.
get()
task_share.Queue.get (self, in_ISR = False)
Read an item from the queue.
If there isn't anything in there, wait (blocking the calling process) until something becomes available. If non-blocking reads are needed, one should call any() to check for items before attempting to read from the queue. This is usually done in a low priority task:
def some_task ():
    # Setup
    while True:
        if my_queue.any ():
            something = my_queue.get ()
            do_something_with (something)
        # More loop stuff
        yield 0
Parameters
in_ISR Set this to True if calling from within an ISR
Definition at line 222 of file task_share.py.
    def get(self, in_ISR=False):
        # Wait until there's something in the queue to be returned
        while self.empty():
            pass
 
        # Prevent data corruption by blocking interrupts during data transfer
        if self._thread_protect and not in_ISR:
            irq_state = pyb.disable_irq()
 
        # Get the item to be returned from the queue
        to_return = self._buffer[self._rd_idx]
 
        # Move the read pointer and adjust the number of items in the queue
        self._rd_idx += 1
        if self._rd_idx >= self._size:
            self._rd_idx = 0
        self._num_items -= 1
        if self._num_items < 0:
            self._num_items = 0
 
        # Re-enable interrupts
        if self._thread_protect and not in_ISR:
            pyb.enable_irq(irq_state)
 
        return to_return
 
References _buffer, _rd_idx, _size, task_share.BaseShare._thread_protect, and empty().
num_in()
task_share.Queue.num_in (self)
Check how many items are in the queue.
This method returns the number of items which are currently in the queue.
Returns
The number of items in the queue
Definition at line 281 of file task_share.py.
    def num_in(self):
        return self._num_items
 
References _num_items.
put()
task_share.Queue.put (self, item, in_ISR = False)
Put an item into the queue.
If there isn't room for the item, wait (blocking the calling process) until room becomes available, unless the overwrite constructor parameter was set to True to allow old data to be clobbered. If non-blocking behavior without overwriting is needed, one should call full() to ensure that the queue is not full before putting data into it:
def some_task ():
    # Setup
    while True:
        if not my_queue.full ():
            my_queue.put (create_something_to_put ())
        yield 0
Parameters
item The item to be placed into the queue
in_ISR Set this to True if calling from within an ISR
Definition at line 173 of file task_share.py.
    def put(self, item, in_ISR=False):
        # If we're in an ISR and the queue is full and we're not allowed to
        # overwrite data, we have to give up and exit
        if self.full():
            if in_ISR:
                return
 
            # Wait (if needed) until there's room in the buffer for the data
            if not self._overwrite:
                while self.full():
                    pass
 
        # Prevent data corruption by blocking interrupts during data transfer
        if self._thread_protect and not in_ISR:
            _irq_state = pyb.disable_irq()
 
        # Write the data and advance the counts and pointers
        self._buffer[self._wr_idx] = item
        self._wr_idx += 1
        if self._wr_idx >= self._size:
            self._wr_idx = 0
        self._num_items += 1
        if self._num_items >= self._size: # Can't be fuller than full
            self._num_items = self._size
        if self._num_items > self._max_full: # Record maximum fillage
            self._max_full = self._num_items
 
        # Re-enable interrupts
        if self._thread_protect and not in_ISR:
            pyb.enable_irq(_irq_state)
 
References _buffer, _overwrite, _size, task_share.BaseShare._thread_protect, _wr_idx, and full().
Member Data Documentation
_buffer
task_share.Queue._buffer = array.array(type_code, range(size)) [protected]
Definition at line 139 of file task_share.py.
_max_full
task_share.Queue._max_full [protected]
Definition at line 197 of file task_share.py.
_name
task_share.Queue._name = None else "Queue" + str(Queue.ser_num) [protected]
Definition at line 134 of file task_share.py.
_num_items
int task_share.Queue._num_items = self._size [protected]
Definition at line 196 of file task_share.py.
_overwrite
task_share.Queue._overwrite = overwrite [protected]
Definition at line 133 of file task_share.py.
_rd_idx
int task_share.Queue._rd_idx = 0 [protected]
Definition at line 237 of file task_share.py.
_size
task_share.Queue._size = size [protected]
Definition at line 132 of file task_share.py.
_wr_idx
int task_share.Queue._wr_idx = 0 [protected]
Definition at line 193 of file task_share.py.
ser_num
int task_share.Queue.ser_num = 0 [static]
A counter used to give serial numbers to queues for diagnostic use.
Definition at line 101 of file task_share.py.
The documentation for this class was generated from the following file:
Lab Final/Files On Romi/task_share.py